/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seaboat_Thread */

#ifndef _Included_com_seaboat_Thread
#define _Included_com_seaboat_Thread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seaboat_Thread
 * Method:    yield0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seaboat_Thread_yield0
  (JNIEnv *, jobject);

/*
 * Class:     com_seaboat_Thread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seaboat_Thread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
